/* FILENAME: UNITS.H
 * PROGRAMMER: OD6
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 07.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Функция создания объекта анимации */
od6UNIT * OD6_ClockUnitCreate( VOID );

od6UNIT * OD6_CubeUnitCreate( VOID );

od6UNIT * OD6_CowUnitCreate( VOID );

/* Функция создания информационного объекта анимации */
od6UNIT * OD6_InfoUnitCreate( VOID );

#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
